stages:
  - build
  - test
  - docker-build

build:
  stage: build
  image: node
  script:
    - echo "start building App"
    - npm install
    - npm run build
    - echo "Build successfully"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test succesfully"

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:20.10.17-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"


