stages:
  - build
  - test
  - docker-build-production
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "start building App"
    - npm install
    - npm run build
    - echo "Build successfully"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test succesfully"

docker-build:
  stage: docker-build-production
  image: docker:latest
  services:
    - name: docker:20.10.17-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - production

deploy:
  stage: deploy
  before_script:
    - CHMOD 400 $SSH_KEY_MINIKUBE
  script: 
    - ssh -o StrictHostKeyCheck=no -i $SSH_KEY_MINIKUBE root@192.168.49.2 "
       docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY &&
       docker ps -aq | xargs docker stop | xargs docker rm &&
       docker run -p 5000:5000 $CI_REGISTRY_IMAGE
    "
    

