stages:
  - build
  - test
  - docker-build-test
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "start building App"
    - npm install
    - npm run build
    - echo "Build successfully"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test succesfully"

docker-build:
  stage: docker-build-test
  image: docker:latest
  services:
    - name: docker:20.10.17-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - test

deploy:
  stage: deploy
  before_script:
    - CHMOD 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyCheck=no -i $SSH_KEY root@178.62.28.179
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY 
    - docker ps -aq | xargs docker stop | xargs docker rm 
    - docker run -d -p 5000:5000 $CI_REGISTRY_IMAGE




